//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MZ3ppc.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MZ3_FORM                    101
#define IDD_OPTIONTAB_PROXY             108
#define IDD_OPTIONTAB_GETPAGE           112
#define IDD_WRITEVIEW                   113
#define IDD_OPTIONTAB_GENERAL           115
#define IDR_MAINFRAME                   128
#define IDR_MZ3TYPE                     129
#define IDR_MAINFRAME2                  129
#define IDR_MAINFRAME_WIN32             130
#define IDR_TOOLBAR                     131
#define IDR_BODY_MENU                   134
#define IDR_REPORT_MENU                 137
#define IDI_NO_PHOTO_ICON               139
#define IDI_PHOTO_ICON                  140
#define IDR_IMAGE_MENU                  140
#define IDR_WRITE_MENU                  141
#define IDR_DIARY_MENU                  142
#define IDR_TOOLBAR_QVGA                145
#define IDD_DEBUG_DIALOG                145
#define IDD_QUOTE_DIALOG                146
#define IDR_TOOLBAR_WIN32               146
#define IDR_PROFILE_ITEM_MENU           147
#define IDD_DEBUG2_DIALOG               148
#define IDR_CATEGORY_MENU               149
#define IDR_ATTACH_IMAGE_MENU           150
#define IDD_COMMON_SELECT_DIALOG        151
#define IDR_SKIN_MENU                   152
#define IDD_USER_DIALOG                 154
#define IDI_TOPIC_ICON                  157
#define IDI_EVENT_ICON                  158
#define IDD_CHOOSE_ACCESS_TYPE_DIALOG   158
#define IDI_ENQUETE_ICON                159
#define IDD_OPEN_URL_DIALOG             159
#define IDI_DOWNLOADED_ICON             160
#define IDI_EVENT_JOIN_ICON             161
#define IDC_GRABBABLE_CURSOR            162
#define IDI_BIRTHDAY_ICON               162
#define IDC_GRABBING_CURSOR             163
#define IDR_TWITTER_MENU                165
#define IDR_TAB_MENU                    166
#define IDD_COMMON_EDIT_DIALOG          167
#define IDR_RSS_MENU                    167
#define IDC_ARROW_LEFT_CURSOR           168
#define IDC_ARROW_RIGHT_CURSOR          169
#define IDB_SLIDE_LEFT_BITMAP           170
#define IDB_SLIDE_RIGHT_BITMAP          172
#define IDI_SCHEDULE_ICON               173
#define IDD_ABOUTBOX_WIDE               200
#define IDC_STATIC_1                    201
#define IDD_REPORTVIEW                  201
#define IDC_STATIC_2                    202
#define IDD_CHOOSE_FONT_DIALOG          202
#define IDC_STATIC_3                    203
#define IDD_OPTIONTAB_UI                203
#define IDC_STATIC_4                    204
#define IDD_OPTIONTAB_LOG               204
#define IDC_STATIC_5                    205
#define IDD_OPTIONTAB_REPORT            205
#define IDC_STATIC_6                    206
#define IDD_OPTIONTAB_DISPLAY           206
#define IDC_STATIC_7                    207
#define IDD_OPTIONTAB_MAIN_VIEW         207
#define IDC_STATIC_8                    208
#define IDD_DOWNLOADVIEW                208
#define IDC_STATIC_9                    209
#define IDD_OPTIONTAB_TWITTER           209
#define IDC_STATIC_10                   210
#define IDD_CHOOSE_CLIENT_TYPE_DIALOG   210
#define IDC_STATIC_11                   211
#define IDC_STATIC_12                   212
#define IDC_STATIC_13                   213
#define IDC_TOTAL_BYTES_STATIC          214
#define IDS_NEW                         301
#define IDS_MENU                        302
#define IDM_NEW                         401
#define IDM_MENU                        402
#define IDC_INFO_EDIT                   1000
#define IDC_HEADER_LIST                 1001
#define IDC_BODY_LIST                   1002
#define IDC_PROGRESS                    1003
#define IDC_REPORT_LIST                 1004
#define IDC_LOGIN_MAIL_EDIT             1007
#define IDC_LOGIN_PASSWORD_EDIT         1008
#define IDC_PROXY_USE_CHECK             1014
#define IDC_PROXY_SERVER_EDIT           1015
#define IDC_PROXY_PORT_EDIT             1016
#define IDC_PAGE_USELOG_CHECK           1020
#define IDC_PAGE_GETALL_RADIO           1021
#define IDC_PAGE_GETLATEST_RADIO        1022
#define IDC_PROXY_USER_EDIT             1023
#define IDC_PROXY_PASSWPRD_EDIT         1024
#define IDC_TITLE_EDIT                  1025
#define IDC_EDIT1                       1027
#define IDC_FONT_BIG_EDIT               1027
#define IDC_SAMPLE_EDIT                 1027
#define IDC_LOGFOLDER_EDIT              1027
#define IDC_QUOTE_MARK_EDIT             1027
#define IDC_SCROLL_LINE_EDIT            1027
#define IDC_INTERVAL_CHECK_SEC_EDIT     1027
#define IDC_URL_EDIT                    1027
#define IDC_STATUS_EDIT                 1027
#define IDC_WRITE_BODY_EDIT             1028
#define IDC_FONT_MEDIUM_EDIT            1028
#define IDC_MESSAGE_EDIT                1028
#define IDC_EDIT2                       1028
#define IDC_WRITE_TITLE_EDIT            1029
#define IDC_FONT_SMALL_EDIT             1029
#define IDC_WRITE_SEND_BUTTON           1030
#define IDC_LONG_RETURN_RANGE_MSEC_EDIT 1030
#define IDC_WRITE_CANCEL_BUTTON         1031
#define IDC_WRITE_INFO_EDIT             1032
#define IDC_BOOT_MNC_CHECK              1033
#define IDC_USE_BGIMAGE_CHECK           1035
#define IDC_USE_LOG_CHECK               1035
#define IDC_SAVE_LOG_CHECK              1035
#define IDC_CONVERT_URL_FOR_MIXI_MOBILE_CHECK 1035
#define IDC_USE_AUTOCONNECTION_CHECK    1035
#define IDC_CONTINUE_CHECK              1035
#define IDC_SERVICE_TYPE_MIXI_CHECK     1035
#define IDC_USE_RAN2_PAN_SCROLL_ANIMATION_CHECK 1035
#define IDC_NO_INTEGRATED_MODE_CHECK    1035
#define IDC_USE_LEFTSOFTKEY_CHECK       1036
#define IDC_DEBUG_MODE_CHECK            1036
#define IDC_SERVICE_TYPE_TWITTER_CHECK  1036
#define IDC_CONFIRM_OPEN_URL_CHECK      1036
#define IDC_USE_XCRAWL_CANCELER_CHECK   1037
#define IDC_SERVICE_TYPE_WASSR_CHECK    1037
#define IDC_DEBUG_LIST                  1038
#define IDC_TYPE_LIST                   1038
#define IDC_USE_RUN_CONFIRM_DLG_CHECK   1038
#define IDC_ACCESS_TYPE_LIST            1038
#define IDC_GROUP_TAB                   1039
#define IDC_CHANGE_LOG_FOLDER_BUTTON    1040
#define IDC_SHOW_ICON_CHECK             1040
#define IDC_PROGRESS_BAR                1041
#define IDC_RECV_BUF_COMBO              1042
#define IDC_SHOW_MINI_IMAGE_CHECK       1042
#define IDC_AUTO_LOAD_MINI_IMAGE_CHECK  1043
#define IDC_RESET_TOTAL_RECV_BYTES_BUTTON 1044
#define IDC_RESET_TAB_BUTTON            1046
#define IDC_SELECT_FONT_BUTTON          1047
#define IDC_FONT_LIST                   1047
#define IDC_SCROLL_LINE_RADIO           1049
#define IDC_SCROLL_PAGE_RADIO           1050
#define IDC_CLEAN_LOG_BUTTON            1050
#define IDC_USE_GLOBAL_PROXY_RADIO      1051
#define IDC_USE_MANUAL_PROXY_RADIO      1052
#define IDC_SELECT1_BUTTON              1052
#define IDC_SELECT2_BUTTON              1053
#define IDC_MESSAGE_STATIC              1054
#define IDC_ENCODING_COMBO              1057
#define IDC_ITEM_LIST                   1061
#define IDC_START_BUTTON                1062
#define IDC_START_STOP_BUTTON           1062
#define IDC_STOP_BUTTON                 1063
#define IDC_EXIT_BUTTON                 1063
#define IDC_VSCROLLBAR                  1063
#define IDC_ID_STATIC                   1064
#define IDC_PASSWORD_STATIC             1065
#define IDC_TYPE_COMBO                  1066
#define IDC_UPDATE_BUTTON               1067
#define IDC_ADD_SOURCE_TEXT_ON_POST_CHECK 1068
#define IDC_STATIC_COPYRIGHT1           1069
#define IDC_TWITTER_RELOAD_TL_AFTER_POST_CHECK 1070
#define IDC_WRITE_VIEWLIMIT_COMBO       1072
#define IDC_STATUS_LINE_COUNT_COMBO     1073
#define IDC_USE_RAN2_HORIZONTAL_DRAG_MOVE_CHECK 1074
#define IDC_TWITTER_GET_PAGE_COUNT_COMBO 1074
#define IDC_USE_RAN2_DOUBLECLICK_MOVE_CHECK 1075
#define IDC_TWITTER_POST_FOOTER_TEXT_EDIT 1076
#define IDC_STATIC_FDQ_TEXT             1077
#define IDC_STATIC_FDQ_COPYRIGHT        1078
#define ID_SETTING                      32772
#define ID_STOP_BUTTON                  32773
#define ID_SETTING_LOGIN                32775
#define ID_GET_ALL                      32779
#define ID_GET_LAST                     32780
#define ID_BACK_BUTTON                  32781
#define ID_SETTING_GENERAL              32783
#define ID_MENU_CLOSE                   32785
#define ID_ADD_BOOKMARK                 32787
#define ID_DEL_BOOKMARK                 32789
#define ID_IMAGE_LOAD                   32797
#define ID_IMAGE_BUTTON                 32799
#define ID_32800                        32800
#define ID_WRITE_COMMENT                32802
#define ID_FORWARD_BUTTON               32803
#define ID_WRITE_BUTTON                 32804
#define ID_EDIT_CPPY                    32808
#define ID_WRITE_SEND_BUTTON            32814
#define ID_WRITE_CANCEL_BUTTON          32816
#define ID_WRITE_SEND_MENU              32817
#define ID_WRITE_CANCEL_MENU            32818
#define ID_WRITE_BACK_MENU              32820
#define ID_BOOKMARK                     32823
#define ID_EDIT                         32824
#define ID_WRITE_DIARY                  32826
#define ID_WRITE_MESSAGE                32828
#define ID_OPEN_BROWSER                 32830
#define ID_SELECT_ALL                   32832
#define ID_BROWSE_BUTTON                32841
#define IDM_GETPAGE_LATEST10            32845
#define IDM_GETPAGE_ALL                 32846
#define ID_SHOW_DEBUG_INFO              32849
#define ID_OPEN_BROWSER_USER            32851
#define ID_CHANGE_FONT_BIG              32857
#define ID_CHANGE_FONT_MEDIUM           32858
#define ID_CHANGE_FONT_SMALL            32859
#define ID_CHANGE_FONT_NORMAL           32861
#define ID_GET_LAST10                   32862
#define ID_MENU_BACK                    32864
#define ID_MENU_NEXT                    32868
#define ID_VIEW_LOG                     32870
#define ID_BACK_MENU                    32873
#define ID_NEXT_MENU                    32874
#define ID_OPEN_SELFINTRO               32877
#define ID_OPEN_INTRO                   32878
#define IDM_DUMMY_PAGE_LINK             32882
#define IDM_CHECK_NEW                   32884
#define IDM_RELOAD_PAGE                 32885
#define IDM_SET_NOT_READ                32888
#define IDM_SET_NO_READ                 32889
#define IDM_VIEW_                       32891
#define IDM_VIEW_BBS_LIST               32892
#define IDM_VIEW_BBS_LIST_LOG           32897
#define IDM_CRUISE                      32901
#define ID_HELP_MENU                    32904
#define ID_HISTORY_MENU                 32906
#define IDM_CHECK_CRUISE                32908
#define IDM_START_CRUISE                32910
#define ID_ATTACH_PHOTO1                32914
#define ID_ATTACH_PHOTO2                32915
#define ID_ATTACH_PHOTO3                32916
#define ID_CANCEL_ATTACH_PHOTO1         32924
#define ID_CANCEL_ATTACH_PHOTO2         32925
#define ID_CANCEL_ATTACH_PHOTO3         32926
#define ID_ATTACH_PHOTO                 32928
#define ID_NEW_MESSAGE                  32930
#define ID_SEND_NEW_MESSAGE             32931
#define ID_PREVIEW_ATTACHED_PHOTO1      32932
#define ID_PREVIEW_ATTACHED_PHOTO2      32933
#define ID_PREVIEW_ATTACHED_PHOTO3      32934
#define IDM_OPEN_MIXI_MOBILE_BY_BROWSER 32943
#define IDM_START_CRUISE_UNREAD_ONLY    32945
#define ID_ERRORLOG_MENU                32948
#define ID_MENU_SKIN_BASE               32951
#define ID_SETTING_SKIN                 32952
#define ID_CHANGE_SKIN                  32953
#define ID_SKIN_DUMMY                   32954
#define IDM_LAYOUT_CATEGORY_            32958
#define IDM_LAYOUT_CATEGORY_WIDEN       32959
#define IDM_LAYOUT_CATEGORY_MAKE_WIDE   32960
#define IDM_LAYOUT_CATEGORY_MAKE_NARROW 32961
#define IDM_LAYOUT_REPORTLIST_MAKE_NARROW 32964
#define IDM_LAYOUT_REPORTLIST_MAKE_WIDE 32966
#define ID_MENU_ACTION                  32969
#define ID_ENABLE_INTERVAL_CHECK        32972
#define ID_SET_INTERVAL_CHECK           32974
#define ID_ACCELERATOR_FONT_MAGNIFY     32975
#define ID_ACCELERATOR_FONT_SHRINK      32976
#define ID_ACCELERATOR_NEXT_TAB         32982
#define ID_ACCELERATOR_PREV_TAB         32983
#define ID_ACCELERATOR_CONTEXT_MENU     32984
#define IDM_SET_READ                    32987
#define ID_ACCELERATOR_RELOAD           32988
#define IDM_INSERT_EMOJI_BEGIN          32994
#define IDM_INSERT_EMOJI_END            33994
#define ID_DOWNLOAD_MANAGER_VIEW        33996
#define ID_OPEN_PROFILE                 34000
#define ID_OPEN_PROFILE_LOG             34003
#define ID_SEND_MESSAGE                 34004
#define ID_MENU_TWITTER_READ            34013
#define ID_MENU_TWITTER_REPLY           34014
#define ID_MENU_TWITTER_UPDATE          34016
#define ID_MENU_TWITTER_HOME            34020
#define ID_MENU_TWITTER_FAVORITES       34021
#define ID_MENU_TWITTER_SITE            34022
#define ID_MENU_TWITTER_FRIEND_TIMELINE 34025
#define ID_TABMENU_DELETE               34028
#define ID_APPEND_MENU_BEGIN            34032
#define ID_APPEND_MENU_END              34132
#define ID_REMOVE_CATEGORY_ITEM         34133
#define ID_EDIT_CATEGORY_ITEM           34135
#define ID_TABMENU_EDIT                 34137
#define ID_TABMENU_ADD                  34139
#define ID_AUTO_RELOAD_BUTTON           34141
#define ID_MENU_TWITTER_NEW_DM          34143
#define ID_MENU_TWITTER_CREATE_FAVOURINGS 34146
#define ID_MENU_TWITTER_DESTROY_FAVOURINGS 34147
#define ID_MENU_TWITTER_CREATE_FRIENDSHIP 34150
#define ID_MENU_TWITTER_CREATE_FRIENDSHIPS 34151
#define ID_MENU_TWITTER_DESTROY_FRIENDSHIPS 34152
#define ID_MENU_OPEN_URL                34155
#define ID_MENU_OPEN_LOCAL_FILE         34157
#define ID_MENU_RSS_READ                34160
#define IDR_RAN2_MENU_URL_LINK          34161
#define ID_RAN2_URL_LINK_OPEN           34162
#define ID_RAN2_URL_LINK_COPY           34163
#define IDM_CATEGORY_OPEN               34164
#define ID_ADD_RSS_FEED_MENU            34166
#define ID_MENU_MIXI_ECHO_READ          34167
#define ID_MENU_MIXI_ECHO_UPDATE        34168
#define ID_MENU_MIXI_ECHO_SHOW_PROFILE  34170
#define ID_ACCELERATOR_TOGGLE_INTEGRATED_MODE 34171
#define ID_MENU_WASSR_READ              34175
#define ID_MENU_WASSR_UPDATE            34177
#define ID_MENU_FONT_MAGNIFY            34180
#define ID_MENU_FONT_SHRINK             34181
#define ID_MENU_MIXI_ECHO_REPLY         34183
#define ID_34184                        34184
#define ID_MENU_PREV_DIARY              34185
#define ID_MENU_NEXT_DIARY              34186
#define ID_MENU_PREVDIARY               34187
#define ID_34188                        34188
#define ID_MENU_MIXI_ECHO_ADD_USER_ECHO_LIST 34192
#define ID_MENU_MIXI_ECHO_ADD_REF_USER_ECHO_LIST 34193
#define IDM_LOAD_FULL_DIARY             34194
#define ID_MENU_CHECK_UPDATE            34196
#define ID_MENU_GOOHOME_READ            34197
#define ID_MENU_GOOHOME_UPDATE          34198
#define ID_MENU_GOOHOME_READ_COMMENTS   34200
#define ID_REPORT_IMAGE                 36000
#define ID_REPORT_URL_BASE              36100
#define ID_REPORT_PAGE_LINK_BASE        36200
#define ID_REPORT_MOVIE                 36300
#define ID_SKIN_BASE                    36400
#define ID_REPORT_COPY_URL_BASE         36500
#define ID_REPORT_COPY_IMAGE            36600
#define ID_REPORT_COPY_MOVIE            36700

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         34201
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
